max_watch_streams: 15
priority:
  - DROPS
  - ORDER
  - STREAK
features:
  claim_drops_startup: true
category_watcher:
  enabled: true
  poll_interval: 60s
  drops_only: true
  campaign_reminders:
    - on_detection
    - 3d
    - 1d
  categories:
    - slug: tom-clancys-rainbow-six-siege
      drops_only: false
team_watcher:
  enabled: true
  poll_interval: 180s
  teams:
    - name: rainbow6
streamer_defaults:
  make_predictions: true
  follow_raid: false
  claim_drops: true
  claim_moments: true
  watch_streak: true
  chat: ALWAYS
  bet:
    strategy: SMART
    percentage: 5
    percentage_gap: 20
    max_points: 50000
    minimum_points: 20000
    stealth_mode: true
    delay: 6
    delay_mode: FROM_END
streamers:
  - username: Guliveer_
  - username: rainbow6
  - username: rainbow6bravo
  - username: rainbow6LATAM
  - username: rainbow6pl
  - username: Pengu
  - username: Skittlz
  - username: itsSpoit
  - username: KingGeorge
  - username: AnneMunition
  - username: Beaulo
  - username: MacieJay
  - username: Interro
  - username: zironicdk
  - username: Athieno
followers:
  enabled: true
notifications:
  batch:
    enabled: true
    interval: 3h
    max_entries: 15
  telegram:
    enabled: true
    events:
      - DROP_CLAIM
      - CAMPAIGN_STARTED
      - CAMPAIGN_REMINDER
      - GIFTED_SUB
      - MINER_STARTED
      - MINER_STOPPED
      - MINER_CRASHED
    disable_notification: true
  webhook:
    method: POST
